import { PaginationResponse } from "@/lib/api/base.types";

export interface User {
  id: string;
  createdAt: string;
  name: string;
  avatar: string;
  city: string;
  cityName: string;
  country: string;
  address: string;
  skin: string;
}

export interface UserSkin {
  id: string;
  skin: string;
}

export interface GetUsersRequest {
  page?: number;
  limit?: number;
  search?: string;
  skins?: string[];
  createdDate?: Date | null;
}

export const fakeUserSkins: UserSkin[] = [
  { id: '1', skin: 'black' },
  { id: '2', skin: 'white' },
  { id: '3', skin: 'yellow' },
  { id: '4', skin: 'indian' },
];

export interface GetUsersResponse extends PaginationResponse<User>{};

export type GetUserByIdResponse = User;

// Users mock data
export const fakeUsers: User[] = [
    {
    id: '1',
    createdAt: '2026-05-19T16:23:17.627Z',
    name: 'Alice Will',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/65.jpg',
    city: 'Jessport',
    cityName: 'Fort Adela',
    country: 'Ukraine',
    address: 'Northeast',
    skin: 'olive',
  },
  {
    id: '2',
    createdAt: '2026-05-20T00:42:29.885Z',
    name: 'Inez Upton',
    avatar: 'https://avatars.githubusercontent.com/u/49957570',
    city: 'Windlerhaven',
    cityName: 'South Loriside',
    country: 'Venezuela',
    address: 'Northeast',
    skin: 'purple',
  },
  {
    id: '3',
    createdAt: '2026-05-19T19:19:11.671Z',
    name: 'Dr. Kelly Hackett DDS',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/86.jpg',
    city: 'Aidenhaven',
    cityName: 'Lake Amos',
    country: 'Grenada',
    address: 'Northwest',
    skin: 'orange',
  },
  {
    id: '4',
    createdAt: '2026-05-20T03:25:22.881Z',
    name: 'Jay Mante DVM',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/21.jpg',
    city: 'Providence',
    cityName: 'Alpharetta',
    country: 'Togo',
    address: 'Northeast',
    skin: 'blue',
  },
  {
    id: '5',
    createdAt: '2026-05-20T05:00:26.802Z',
    name: 'Cory Mayert I',
    avatar: 'https://avatars.githubusercontent.com/u/27031268',
    city: 'Lehi',
    cityName: 'Jerdeworth',
    country: 'Thailand',
    address: 'Northeast',
    skin: 'lavender',
  },
  {
    id: '6',
    createdAt: '2026-05-19T18:01:19.461Z',
    name: "Jo O'Connell",
    avatar: 'https://avatars.githubusercontent.com/u/11081120',
    city: 'Shoreline',
    cityName: 'South Cristopher',
    country: 'Mali',
    address: 'North',
    skin: 'fuchsia',
  },
  {
    id: '7',
    createdAt: '2026-05-20T13:55:44.521Z',
    name: 'Miriam Kemmer',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/93.jpg',
    city: 'Arloshire',
    cityName: 'New Annacester',
    country: 'France',
    address: 'South',
    skin: 'fuchsia',
  },
  {
    id: '8',
    createdAt: '2026-05-20T06:59:01.285Z',
    name: 'Raquel Dietrich',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/81.jpg',
    city: 'East Talia',
    cityName: 'Baltimore',
    country: 'Uganda',
    address: 'Southeast',
    skin: 'orchid',
  },
  {
    id: '9',
    createdAt: '2026-05-20T15:33:58.317Z',
    name: 'Antoinette Dietrich',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/24.jpg',
    city: 'Port Antonettaberg',
    cityName: 'South Chad',
    country: 'Ghana',
    address: 'South',
    skin: 'turquoise',
  },
  {
    id: '10',
    createdAt: '2026-05-20T10:23:44.455Z',
    name: 'Cecelia Jaskolski',
    avatar: 'https://avatars.githubusercontent.com/u/37700455',
    city: 'East Novafort',
    cityName: 'West Nelda',
    country: 'Western Sahara',
    address: 'Northeast',
    skin: 'mint green',
  },
  {
    id: '11',
    createdAt: '2026-05-20T03:43:55.515Z',
    name: 'Edith Luettgen',
    avatar: 'https://avatars.githubusercontent.com/u/85544550',
    city: 'Reinholdport',
    cityName: 'Monicaberg',
    country: 'Cambodia',
    address: 'Southeast',
    skin: 'teal',
  },
  {
    id: '12',
    createdAt: '2026-05-20T07:21:08.755Z',
    name: 'Claire Hirthe',
    avatar: 'https://avatars.githubusercontent.com/u/6088350',
    city: 'Stamford',
    cityName: 'Juwanhaven',
    country: 'Cyprus',
    address: 'Northwest',
    skin: 'cyan',
  },
  {
    id: '13',
    createdAt: '2026-05-20T00:48:31.020Z',
    name: 'Dr. Elijah Hauck V',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/62.jpg',
    city: 'Kossborough',
    cityName: 'East Brandthaven',
    country: 'Serbia',
    address: 'Northeast',
    skin: 'lavender',
  },
  {
    id: '14',
    createdAt: '2026-05-20T03:18:41.518Z',
    name: 'Ellis Kemmer',
    avatar: 'https://avatars.githubusercontent.com/u/58104238',
    city: 'Phoenix',
    cityName: 'Lake Naomibury',
    country: 'Benin',
    address: 'Northeast',
    skin: 'green',
  },
  {
    id: '15',
    createdAt: '2026-05-19T23:28:48.391Z',
    name: 'Elbert Maggio',
    avatar: 'https://avatars.githubusercontent.com/u/36462965',
    city: 'Windlershire',
    cityName: 'Lake Jaronland',
    country: 'Portugal',
    address: 'Northeast',
    skin: 'azure',
  },
    {
    id: '16',
    createdAt: '2026-05-20T00:37:56.474Z',
    name: 'Mr. Lowell Hirthe',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/43.jpg',
    city: 'North Perry',
    cityName: 'East Jeremy',
    country: 'Montenegro',
    address: 'East',
    skin: 'gold',
  },
  {
    id: '17',
    createdAt: '2026-05-20T10:54:19.227Z',
    name: 'Russell Sauer',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/33.jpg',
    city: 'South Nicklausstead',
    cityName: 'Santa Rosa',
    country: 'Cayman Islands',
    address: 'East',
    skin: 'tan',
  },
  {
    id: '18',
    createdAt: '2026-05-20T05:53:04.286Z',
    name: 'Edgar Boyle MD',
    avatar: 'https://avatars.githubusercontent.com/u/15375009',
    city: 'Cronaboro',
    cityName: 'Weimannshire',
    country: 'Botswana',
    address: 'Northeast',
    skin: 'gold',
  },
  {
    id: '19',
    createdAt: '2026-05-20T00:19:32.777Z',
    name: 'Gustavo Sanford',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/5.jpg',
    city: 'Hansenboro',
    cityName: 'Dibbertfurt',
    country: 'Russian Federation',
    address: 'West',
    skin: 'lavender',
  },
  {
    id: '20',
    createdAt: '2026-05-19T18:01:40.232Z',
    name: 'Deanna Rath',
    avatar: 'https://avatars.githubusercontent.com/u/47960291',
    city: 'Lake Elbert',
    cityName: 'Jefferson City',
    country: 'Western Sahara',
    address: 'Southwest',
    skin: 'mint green',
  },
  {
    id: '21',
    createdAt: '2026-05-20T02:33:33.200Z',
    name: 'Gilbert Schaefer',
    avatar: 'https://avatars.githubusercontent.com/u/36511349',
    city: 'Reichertshire',
    cityName: 'Reynoldsfort',
    country: 'Sweden',
    address: 'East',
    skin: 'black',
  },
  {
    id: '22',
    createdAt: '2026-05-20T06:04:07.757Z',
    name: 'Armando Lubowitz V',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/30.jpg',
    city: 'Flatleyborough',
    cityName: 'West Kristian',
    country: 'Guernsey',
    address: 'East',
    skin: 'orange',
  },
  {
    id: '23',
    createdAt: '2026-05-20T14:16:25.484Z',
    name: 'Cynthia Gulgowski',
    avatar: 'https://avatars.githubusercontent.com/u/68660683',
    city: 'Port Loyal',
    cityName: 'South Katelincester',
    country: 'American Samoa',
    address: 'Southeast',
    skin: 'lavender',
  },
  {
    id: '24',
    createdAt: '2026-05-20T11:33:20.401Z',
    name: 'Ricky Nitzsche',
    avatar: 'https://avatars.githubusercontent.com/u/5959335',
    city: 'Redwood City',
    cityName: 'Kettering',
    country: 'Hong Kong',
    address: 'Southwest',
    skin: 'turquoise',
  },
  {
    id: '25',
    createdAt: '2026-05-20T03:58:11.037Z',
    name: 'Grady Fay',
    avatar: 'https://avatars.githubusercontent.com/u/95967402',
    city: 'Downers Grove',
    cityName: 'Douglasboro',
    country: 'Svalbard & Jan Mayen Islands',
    address: 'Southeast',
    skin: 'lavender',
  },
  {
    id: '26',
    createdAt: '2026-05-19T18:09:23.498Z',
    name: 'Homer Kuvalis-Deckow',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/83.jpg',
    city: 'Riverview',
    cityName: 'Inglewood',
    country: 'Dominica',
    address: 'Northwest',
    skin: 'magenta',
  },
  {
    id: '27',
    createdAt: '2026-05-19T20:55:21.295Z',
    name: 'Mrs. Kristy Hickle-Tremblay',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/67.jpg',
    city: 'Kertzmannton',
    cityName: 'Runteshire',
    country: 'Brunei Darussalam',
    address: 'Northeast',
    skin: 'tan',
  },
  {
    id: '28',
    createdAt: '2026-05-20T11:37:00.926Z',
    name: 'Armando Leannon',
    avatar: 'https://avatars.githubusercontent.com/u/98935924',
    city: 'Oakland Park',
    cityName: 'Purdyfurt',
    country: 'Kiribati',
    address: 'South',
    skin: 'blue',
  },
  {
    id: '29',
    createdAt: '2026-05-19T19:53:02.051Z',
    name: 'Pablo Hansen',
    avatar: 'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/4.jpg',
    city: 'Fort Antoniettacester',
    cityName: 'Port Casandraport',
    country: 'Cook Islands',
    address: 'Southeast',
    skin: 'grey',
  },
  {
    id: '30',
    createdAt: '2026-05-19T17:19:15.109Z',
    name: 'Alberta Stanton',
    avatar: 'https://avatars.githubusercontent.com/u/89188486',
    city: 'Darestead',
    cityName: 'Worcester',
    country: 'Eswatini',
    address: 'Southwest',
    skin: 'violet',
  },
];

// user skin mock data
export interface UserSkin {
  id: string;
  skin: string;
}

