
trigger: none

variables:
  - group: fe-variables

  # Agent VM image name
vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build ReactJs
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: NodeTool@0
      displayName: Use Node 24.x
      inputs:
        versionSpec: 24.x
        checkLatest: true
    - task: Npm@1
      displayName: npm install
      inputs:
        workingDir: UI
    - task: Npm@1
      displayName: npm audit --audit-level=critical
      inputs:
        command: 'custom'
        workingDir: 'UI'
        customCommand: 'audit --audit-level=critical'
    - task: Npm@1
      displayName: run build
      inputs:
        command: custom
        workingDir: UI
        customCommand: run build