services:
  # Database
  nam-db:
    container_name: nam-db
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - nam-db-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - path: secrets/nam-db.env
        required: true
    networks:
      - nam-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  # API
  nam-api:
    container_name: nam-api
    image: anonyfriday/api:latest
    restart: always
    depends_on:
      nam-db:
        condition: service_healthy
    ports:
      - 5000:8080
    env_file:
      - path: secrets/nam-api.env
        required: true
    networks:
      - nam-network

  # Web Frontend
  nam-web:
    container_name: nam-web
    image: anonyfriday/web:latest
    restart: always
    depends_on:
      nam-db:
        condition: service_healthy
      nam-api:
        condition: service_started
    ports:
      - 5001:80
    env_file:
      - path: secrets/nam-web.env
        required: true
    networks:
      - nam-network

volumes:
  nam-db-data:


networks:
  nam-network:
    driver: bridge
